SELECT D.DNUMBER AS EMPLOYEE_NUM, COUNT(E.SSN) AS HIGH_SALARY_EMPLOYEE_NUM
FROM DEPARTMENT D
JOIN EMPLOYEE E ON D.DNUMBER = E.DNO
GROUP BY D.DNUMBER
HAVING COUNT(E.SSN) > 2 AND SUM(E.SALARY > 30000);

